/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Blubb: typeof import('./components/Blubb.vue')['default']
    Cost: typeof import('./components/Cost.vue')['default']
    CostTable: typeof import('./components/CostTable.vue')['default']
    DefaultCostTable: typeof import('./components/CostTables/DefaultCostTable.vue')['default']
    PlanePartTable: typeof import('./components/CostTables/PlanePartTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Testing: typeof import('./components/Testing.vue')['default']
  }
}
