/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CalcCostInfo: typeof import('./components/CalcCostInfo.vue')['default']
    CostTable: typeof import('./components/CostTable.vue')['default']
    DataImportExport: typeof import('./components/DataImportExport.vue')['default']
    GlobalDialog: typeof import('./components/GlobalDialog.vue')['default']
    PlaneInfo: typeof import('./components/PlaneInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
