/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Blubb: typeof import('./components/Blubb.vue')['default']
    CalcCostInfo: typeof import('./components/CalcCostInfo.vue')['default']
    Cost: typeof import('./components/Cost.vue')['default']
    CostInfo: typeof import('./components/CostInfo.vue')['default']
    CostTable: typeof import('./components/CostTable.vue')['default']
    CustomSmallDialog: typeof import('./components/CustomSmallDialog.vue')['default']
    DataImportExport: typeof import('./components/DataImportExport.vue')['default']
    DefaultCostInfo: typeof import('./components/CostInfo/DefaultCostInfo.vue')['default']
    DefaultCostTable: typeof import('./components/CostTables/DefaultCostTable.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    GlobalDialog: typeof import('./components/GlobalDialog.vue')['default']
    PlaneInfo: typeof import('./components/PlaneInfo.vue')['default']
    PlanePartCostInfo: typeof import('./components/CostInfo/PlanePartCostInfo.vue')['default']
    PlanePartTable: typeof import('./components/CostTables/PlanePartTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SampleDialogContent: typeof import('./components/SampleDialogContent.vue')['default']
    Testing: typeof import('./components/Testing.vue')['default']
  }
}
